### ISSUE TITLE
Bypass permission does not work on OP or those with permission

### ISSUE THREAD

**Issue by ChiboYen** [Bram1903/AntiHealthIndicator#2]
I've tried testing this a few different ways, and also logging out and logging in every time on both accounts. However, even with OP status or the bypass permission, spoofed data is still sent and the health bar reads "1".

**Comment by Bram1903** [comment]
@ChiboYen, are you sure that in the configuration `allow-bypass` is enabled? It's disabled by default.

**Comment by ChiboYen** [comment]
Thanks for clarifying, perhaps I failed to completely read the part where it said "(can be enabled in the config)", thank you!

**Comment by Bram1903** [comment]
Haha, no problem! Happy to hear it solved your issue!
