### ISSUE TITLE
[Bug] Strange freezing/lag

### ISSUE THREAD

**Issue by ewof** [Bram1903/AntiHealthIndicator#7]
some players report a mini rubberbanding / screen freezing for a second with this plugin, had to go 1 by 1 to see what caused and somehow it was this plugin. i know this isn't really helpful so if there's any relevant info i can give you just ask, also it doesn't happen to me but it happens to a good amount of players. its only clientside

**Comment by Bram1903** [comment]
Hey there, 

Thanks for reporting this issue! I'm am trying to figure out what could be causing these freeze ups as everything is being done asynchronous away from the main thread, but on the other side this sounds like a client side glitch, not necessarily performance. What version and software is your server running and are you using any plugins like ViaVersion?

**Comment by ewof** [comment]
we're on git-Folia-"25ee657" with velocity, we have via version with the packet limiters disabled. to some people it doesnt happen but it happens to some people even on a vanilla minecraft client with no mods

**Comment by Bram1903** [comment]
Alright thank you so much! Since today I'm on vacation and I will back Thursday. I'll try to find a fix this evening on my MacBook!

**Comment by ewof** [comment]
thank u so much for looking into it. there's no rush so you should enjoy your vacation if youd prefer, i dont want to pressure you or anything haha

**Comment by Bram1903** [comment]
I can't quickly find the problem for now. I will look into this more deeply soon!

**Comment by Bram1903** [comment]
This is still on the roadmap, I am just having a hard time finding the time to patch issues. :-)

**Comment by Bram1903** [comment]
Hey @ewof,

I am having a hard time trying to find/reproduce this issue. Technically I am modifying already sent packets that are being sent, not necessarily delaying or sending extra packets. Therefore I don't understand how this could create rubber banding issues.

I asked some of my friends at PacketEvents if they knew what could cause this issue, and they are saying my plugin is impossible to cause such an issue.  Do you perhaps have more information? What kind of people are experiencing issues (extremely bad PC?), etc? 

Kind regards,
Bram

**Comment by Bram1903** [comment]
@ewof, could you try out the latest version 2.1.0 (make sure to update your PacketEvents), and tell me if the issue still occurs?

**Comment by ewof** [comment]
it doesn't happen to me but when they're online i'll check with the people who were having the issue

**Comment by ewof** [comment]
still happens

**Comment by Bram1903** [comment]
Hello @ewof,

Sorry for the long delay. I have been quite busy these past weeks. I am currently working on adding proxy support for both Velocity and Bungeecord (including any forks). Besides that, I added native Folia scheduler support. I hope this somehow solves your issues.

I am not yet sure when I will release this new version as there are still a few complex matters I have to resolve when running this on the proxy, but I am sure we will manage. I thought I'd give you a quick update for now. 

Kind regards,
Bram

**Comment by Bram1903** [comment]
Hey @ewof, 

Can you try the latest release:
https://github.com/Bram1903/AntiHealthIndicator/releases/tag/v2.2.0

It has countless improvements and is much faster than the previous one!

Kind regards,
Bram

**Comment by ewof** [comment]
still happens but on previous versions it was a full freeze and now it's just an FPS drop (but still noticeable)

**Comment by Bram1903** [comment]
> still happens but on previous versions it was a full freeze and now it's just an FPS drop (but still noticeable)

I just don't get it. My plugin simply cannot cause any decrease in performance. Everything that is being done, is done on the server. A client freezing up or having worse FPS is just not possible. My plugin cannot influence that. Sorry, but I can't fix this issue for you.

Kind regards,
Bram
