### ISSUE TITLE
[Bug] Kick when trying to lay with GSit on any slab

### ISSUE THREAD

**Issue by envizar** [Bram1903/AntiHealthIndicator#9]
```
Envizar issued server command: /lay
Envizar lost connection: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "com.github.retrooper.packetevents.protocol.player.EquipmentSlot.getId(com.github.retrooper.packetevents.manager.server.ServerVersion)" because the return value of "com.github.retrooper.packetevents.protocol.player.Equipment.getSlot()" is null
```

Idk if this problem is caused by packetevents, but there's still a chance that it's an AHI error
Version: Paper 1.20.6
Packetevents version: from https://github.com/retrooper/packetevents/actions/runs/9244938821

**Comment by Bram1903** [comment]
Hello, 

Thanks for reporting this issue! I'll try and debug this problem to see if it's related to my plugin or PacketEvents in general. Once I have more information I will get back to you.

Kind regards,
Bram

**Comment by envizar** [comment]
> https://github.com/retrooper/packetevents/issues/803#issuecomment-2140952169

Will you release AHI for bungeecord/waterfall?
(I asked this here because it looks like an offtopic in the packetevents repo)

**Comment by Bram1903** [comment]
> > [retrooper/packetevents#803 (comment)](https://github.com/retrooper/packetevents/issues/803#issuecomment-2140952169)
> 
> Will you release AHI for bungeecord/waterfall? (I asked this here because it looks like an offtopic in the packetevents repo)

Hey, 

Yeah, I will support Bungeecord (and its forks) and Velocity. You can see the current progress in [feat/ProxySupport](https://github.com/Bram1903/AntiHealthIndicator/tree/feat/ProxySupport). I already have it working on both platforms, but I have to fix an issue that came up with the way I cache entities on the proxy, after I fix that it should be ready. Currently, it does work, but it doesn't remove entities from the cache, thus the memory usage constantly keeps going up. 

I am currently getting help from Tofaa and Booky about this matter, and we have probably found a working solution, but we still need to verify that. Unfortunately, we are all a bit busy at the moment, but I have my hopes up I can fix it this weekend. 

Kind regards,
Bram

**Comment by Bram1903** [comment]
> > [retrooper/packetevents#803 (comment)](https://github.com/retrooper/packetevents/issues/803#issuecomment-2140952169)
> 
> Will you release AHI for bungeecord/waterfall? (I asked this here because it looks like an offtopic in the packetevents repo)

https://github.com/Bram1903/AntiHealthIndicator/releases/tag/v2.2.0

;-)

**Comment by Bram1903** [comment]
Hey @envizar, if you use the latest snapshot build from PacketEvents, this issue has now been fixed! Most probably tomorrow PE will release their next release including 1.21 support, but you could already download the SNAPSHOT build.
